apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkspy
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: darkspy
  template:
    metadata:
      name: darkspy
      labels:
        app: darkspy
    spec:
      containers:
        - name: darkspy
          image: darkspy:0.1.0
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: darkspy
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: darkspy
  type: LoadBalancer

